---
apiVersion: v1
kind: Service
metadata:
  name: mysql-metrics
  namespace: monitoring
  labels:
    external-app: mysql-metrics
spec:
  type: ExternalName
  externalName: 47.99.108.202
  ports:
  - name: metrics
    port: 9104
    protocol: TCP
    targetPort: 9104

---
apiVersion: v1
kind: Endpoints
metadata:
  name: mysql-metrics
  namespace: monitoring
  labels:
    external-app: mysql-metrics
subsets:
- addresses:
  - ip: 47.99.108.202
  ports:
  - name: metrics
    port: 9104
    protocol: TCP

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mysql-metrics
  namespace: monitoring
  labels:
    external-app: mysql-metrics
spec:
  selector:
    matchLabels:
      external-app: mysql-metrics
    namespaceSelector:
      matchNames:
      - monitoring
  endpoints:
  - port: metrics
    interval: 10s
    honorLabels: true
    path: /metrics
  targetLabels:
  - external-app